from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [



    path('', RedirectView.as_view(url='home/')),
    path('home/', views.homepage, name='contact'),
    path('subscribe/', views.subscribe, name='subscribe'),



    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('boardresult/', views.boardresult, name='boardresult'),
    path('uniresult/', views.uniresult, name='uniresult'),
    path('pairing/', views.pairing, name='pairing'),
    path('datesheets/', views.datesheets, name='datesheets'),
    path('meritcal/', views.merit, name='merit'),
    path('preperation/', views.preperation, name='preperation'),
    path('boardresult/lahore', views.lahoreboard, name='lahoreboard'),
    path('boardresult/federal', views.federalboard, name='federalboard'),
    path('boardresult/karachi', views.karachiboard, name='karachiboard'),
    path('boardresult/multan', views.multanboard, name='multanboard'),
    path('boardresult/peshawar', views.peshawarboard, name='peshawarboard'),
    path('boardresult/rawalpindi', views.rawalpindiboard, name='rawalpindiboard'),
    path('boardresult/faisalabad', views.faisalabadboard, name='faisalabadboard'),
    path('boardresult/gujranwala', views.gujranwalaboard, name='gujranwalaboard'),
    path('boardresult/hyderabad', views.hyderabadboard, name='hyderabadboard'),
    path('boardresult/abbottabad', views.abbottabadboard, name='abbottabadboard'),
    path('boardresult/mardan', views.mardanboard, name='mardanboard'),
    path('boardresult/sukkur', views.sukkurboard, name='sukkurboard'),
    path('boardresult/sargodha', views.sargodhaboard, name='sargodhaboard'),
    path('boardresult/bannu', views.bannuboard, name='bannuboard'),
    path('boardresult/larkana', views.larkanaboard, name='larkanaboard'),
    path('boardresult/sahiwal', views.sahiwalboard, name='sahiwalboard'),
    path('boardresult/swat', views.swatboard, name='swatboard'),
    path('boardresult/mipurkhas', views.mipurkhasboard, name='mipurkhasboard'),
    path('boardresult/bahawalpur', views.bahawalpurboard, name='bahawalpurboard'),
    path('boardresult/dgkhan', views.dgkhanboard, name='dgkhanboard'),
    path('boardresult/dikhan', views.dikhanboard, name='dikhanboard'),
    path('boardresult/aghakhan', views.aghakhanboard, name='aghakhanboard'),
    path('boardresult/malakand', views.malakandboard, name='malakandboard'),
    path('boardresult/kohat', views.kohatboard, name='kohatboard'),
    path('boardresult/pbte', views.pbteboard, name='pbteboard'),
    path('boardresult/kpbte', views.kpbteboard, name='kpbteboard'),
    path('boardresult/sbte', views.sbteboard, name='sbteboard'),
    path('boardresult/ajk', views.ajkboard, name='ajkboard'),
    path('boardresult/baec', views.baecboard, name='baecboard'),
    path('boardresult/quetta', views.quettaboard, name='quettaboard'),
    path('boardresult/fde', views.fdeboard, name='fdeboard'),
    path('boardresult/doeb', views.doebboard, name='doebboard'),
    path('boardresult/pec', views.pecboard, name='pecboard'),
    path('meritcal/pieas', views.pieas, name='pieascal'),
    path('meritcal/mdcat', views.mdcat, name='mdcatcal'),
    path('meritcal/nust', views.nust, name='nustcal'),
    path('meritcal/uetlahore', views.uetlahore, name='uetlahorecal'),
    path('meritcal/giki', views.giki, name='gikical'),
    path('meritcal/comsats', views.comsats, name='comsatscal'),
    path('meritcal/fast', views.fast, name='fastcal'),
    path('meritcal/gcu', views.gcu, name='gcucal'),
    path('meritcal/pucit', views.pucit, name='pucitcal'),
    path('meritcal/ist', views.ist, name='istcal'),
    path('meritcal/iba', views.iba, name='ibacal'),
    path('meritcal/lums', views.lums, name='lumscal'),
    path('meritcal/uetpeshawar', views.uetpeshawar, name='uetpeshawarcal'),
    path('meritcal/ntu', views.ntu, name='ntucal'),
    path('meritcal/qau', views.qau, name='qaucal'),
    path('meritcal/air', views.air, name='aircal'),
    path('meritcal/bzu', views.bzu, name='bzucal'),
    path('preperation/matric-inter', views.matricinter, name='matricinter'),
    path('preperation/entrytest', views.entrytest, name='entrytest'),
    path('preperation/book-pdf', views.bookpdf, name='bookpdf'),
    path('uniresult/punjab-university', views.puresult, name='puresult'),
    path('uniresult/karachi-university', views.kuresult, name='kuresult'),
    path('uniresult/sargodha-university', views.uosresult, name='uosresult'),
    path('uniresult/peshawar-university', views.uopresult, name='uopresult'),
    path('uniresult/allama-iqbal-university', views.aiouresult, name='aiouresult'),
    path('uniresult/ajk-university', views.ajkresult, name='ajkresult'),
    path('uniresult/islamia-university', views.islamiaresult, name='islamiaresult'),
    path('uniresult/bahauddin-zakariya-university', views.bzuresult, name='bzuresult'),
    path('preperation/book-pdf/5th', views.fifthclassbook, name='fifthclassbook'),
    path('preperation/book-pdf/8th', views.eighthclassbook, name='eighthclassbook'),
    path('preperation/book-pdf/9th', views.ninthclassbook, name='ninthclassbook'),
    path('preperation/book-pdf/10th', views.tenthclassbook, name='tenthclassbook'),
    path('preperation/book-pdf/11th', views.eleventhclassbook, name='eleventhclassbook'),
    path('preperation/book-pdf/12th', views.twelvethclassbook, name='twelvethclassbook'),
    path('prizebond/', views.prizebond, name='prizebond'),
    path('prizebond/schedule', views.prizebondschedule, name='prizebondschedule'),
    path('coronavirus/', views.coronavirus, name='coronavirus'),
    path('comingsoon/', views.comingsoon, name='comingsoon'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
